### ISSUE TITLE
--secondary=no

### ISSUE THREAD

**Issue by zhoudreames** [marbl/Winnowmap#12]
I see your recommed code havent include to this parameter about "--secondary=no".can it  better handle repeat region if I add to this parameter ?

**Comment by zhoudreames** [comment]
@jmarshall @tseemann @lh3 @mcshane

**Comment by cjain7** [comment]
I think you don't need to worry about `--secondary=no` if your concern is accuracy within repeats. `--secondary=no` is supported in minimap2 to avoid secondary alignments in output file; it doesn't affect the algorithm.

You can also do post filtering of primary alignments using samtools.

**Comment by zhoudreames** [comment]
> samtools

thanks~how to fliter primary alignments by using samtools

**Comment by cjain7** [comment]
https://www.biostars.org/p/259963/

**Comment by zhoudreames** [comment]
thank you for your reply~ I use samtools to filter primary alignment,but there are remains un-filterd mulit-mapped show in blow: 
![image](https://user-images.githubusercontent.com/54714639/105955277-fec89180-60b0-11eb-8d1b-a5543e982ef3.png)
in this reads,different part of  one reads were mapped different part of genome.in my ONT data bam file, this case account for 2% in all alignmet reads.i dont why ?and how to solve this problem? thanks
