### ISSUE TITLE
Mapping setting advice

### ISSUE THREAD

**Issue by GuillaumeHolley** [marbl/Winnowmap#13]
Hi,

I am trying to use Winnowmap to map long reads with an error rate around 1.5-3%. I tried both the `map-ont` and `map-pb` presets and the difference between the two can be quite big. Any recommendation on a preset or some specific settings?

Thank you.
Guillaume

**Comment by cjain7** [comment]
What are the read lengths like?

**Comment by GuillaumeHolley** [comment]
Roughly 20 to 25 kb.

**Comment by cjain7** [comment]
You can go with `map-pb` in this case.

**Comment by GuillaumeHolley** [comment]
I appreciate the feedback, thank you!
