### ISSUE TITLE
not compiling on Mac OS

### ISSUE THREAD

**Issue by mleysens** [marbl/Winnowmap#14]
I have latest GCC installed on the Mac. Any thoughts to resolution?

ari:Winnowmap maurice$ make -j8
/Library/Developer/CommandLineTools/usr/bin/make -e -C src
c++ -c  -g -Wall -O2 -DHAVE_KALLOC -fopenmp -std=c++11 -Wno-sign-compare -Wno-write-strings -Wno-unused-but-set-variable  main.c -o main.o
c++ -c  -g -Wall -O2 -DHAVE_KALLOC -fopenmp -std=c++11 -Wno-sign-compare -Wno-write-strings -Wno-unused-but-set-variable  kthread.c -o kthread.o
c++ -c  -g -Wall -O2 -DHAVE_KALLOC -fopenmp -std=c++11 -Wno-sign-compare -Wno-write-strings -Wno-unused-but-set-variable  kalloc.c -o kalloc.o
c++ -c  -g -Wall -O2 -DHAVE_KALLOC -fopenmp -std=c++11 -Wno-sign-compare -Wno-write-strings -Wno-unused-but-set-variable  misc.c -o misc.o
c++ -c  -g -Wall -O2 -DHAVE_KALLOC -fopenmp -std=c++11 -Wno-sign-compare -Wno-write-strings -Wno-unused-but-set-variable  bseq.c -o bseq.o
c++ -c  -g -Wall -O2 -DHAVE_KALLOC -fopenmp -std=c++11 -Wno-sign-compare -Wno-write-strings -Wno-unused-but-set-variable  sketch.c -o sketch.o
c++ -c  -g -Wall -O2 -DHAVE_KALLOC -fopenmp -std=c++11 -Wno-sign-compare -Wno-write-strings -Wno-unused-but-set-variable  sdust.c -o sdust.o
c++ -c  -g -Wall -O2 -DHAVE_KALLOC -fopenmp -std=c++11 -Wno-sign-compare -Wno-write-strings -Wno-unused-but-set-variable  options.c -o options.o
clangclangclang: : : clang: clang: clang: clang: clang: warningwarning: warning: : warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated [-Wdeprecated]treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated [-Wdeprecated]

treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated [-Wdeprecated]
treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated [-Wdeprecated]
warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated [-Wdeprecated]
warning: warningtreating 'c' input as 'c++' when in C++ mode, this behavior is deprecated [-Wdeprecated]:
treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated [-Wdeprecated]
warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated [-Wdeprecated]
clangclang: errorclangclang: : : errorunsupported option '-fopenmp'error: :
unsupported option '-fopenmp'unsupported option '-fopenmp'

: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
make[1]: *** [kthread.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [sketch.o] Error 1
make[1]: *** [kalloc.o] Error 1
make[1]: *** [sdust.o] Error 1
make[1]: *** [misc.o] Error 1
make[1]: *** [options.o] Error 1
make[1]: *** [bseq.o] Error 1
make[1]: *** [main.o] Error 1
make: *** [winnowmap] Error 2

**Comment by cjain7** [comment]
Check #3

**Comment by mleysens** [comment]
see notes related to #3

thanks

**Comment by cjain7** [comment]
Solved in #3
