### ISSUE TITLE
uniq kmer anchoring mapping

### ISSUE THREAD

**Issue by zhoudreames** [marbl/Winnowmap#15]
In T2T chrX centromere article,they mapiing reads by using uniq kmer anchoring method.Do I still need to corrected centromere reads location by uniq kmer method if I use Winowmap2 ?

**Comment by zhoudreames** [comment]
@jmarshall @tseemann @lh3 @mcshane  could you help me ? thank you~

**Comment by cjain7** [comment]
@zhoudreames You can follow the commands mentioned in README. There is no preprocessing needed.
