### ISSUE TITLE
required read length for winnowmap

### ISSUE THREAD

**Issue by charliechen912ilovbash** [marbl/Winnowmap#35]
Hi,

I am using a normal human genome sequenced by Nanopore, to run winnowmap2.
Sequencing depth is 20x, read length N50 is 14 Kb.
I am wondering the recommended minimum read length N50, to obtain reasonable depth after mapping with winnowmap2, like the chromosome X figure in github page.
With my current data, there is no significant difference on depth and mapping rate, between minimap2 and winnowmap2.
I'm not sure if this is because my read length N50 is too short.

Or, should I perform some filtering based on read length ? e.g. only use read > 10 Kb.

Thanks

**Comment by cjain7** [comment]
Hi, apologies for overlooking this.
In case this is still unresolved; the figure on Github page shows minimizer sampling density (count of minimizers considered for seeding stage during read alignment). It does not show the alignment coverage.

Also, that figure was generated by using a minimap2 version which ignored high-frequency Kmers. The [latest version](https://doi.org/10.1093/bioinformatics/btab705) addresses the issue.
