### ISSUE TITLE
equivalent of minimap2 -ax splice -uf -k14 ref.fa direct-rna.fq > aln.sam ? 

### ISSUE THREAD

**Issue by OscarChou211** [marbl/Winnowmap#4]
Hi there, 

I wonder if the software has any equivalent of the minimap2 minimap2 -ax splice -uf -k14 ref.fa direct-rna.fq > aln.sam for the direct RNA sequencing data? 

Thank you for helping!

**Comment by cjain7** [comment]
Hi, I've added the splice option back. Please feel free to try it. 
In your command, since you are changing the k-mer size from 15 to 14; you'd also need to revise meryl command accordingly. 

```
meryl count k=14 output merylDB ref.fa
meryl print greater-than distinct=0.9998 merylDB > repetitive_k14.txt
winnowmap -W repetitive_k14.txt -ax splice -k14 -uf ref.fa direct_rna.fq.gz >  aln.sam
```

**Comment by OscarChou211** [comment]
Dear Chirag Jain, 

Thank you very much for your kindly help! Sorry for my late reply since then! That helps a lot and would provide me with a lot help in the analysis! Really a big thank you! 

Best regards,
