### ISSUE TITLE
kmer size for meryl

### ISSUE THREAD

**Issue by mrvollger** [marbl/Winnowmap#5]
I noticed that the suggested kmer size for merly (k=15) in the README matches the map-ont preset (at least according to the minimap2 man page); however, it does not match the map-pb preset (k=19). Is this intended? I just expected that the kmer sizes would need to be matched to the preset. 

Thanks!
Mitchell

**Comment by cjain7** [comment]
Yes it is intended. map-pb options in winnowmap also use k=15 (instead of 19)

**Comment by mrvollger** [comment]
Thanks!
